/**
 * Variant trigger-comparison launcher (platform-neutral orchestration).
 *
 * Runs every variant of a skill against the SAME implementation task, each in its
 * own interactive terminal window, so you can watch side by side *whether*, *at
 * what point*, and *with what wording* each variant triggers its review.
 *
 * Usage:
 *   deno task variants <taskId> [--skill <name>]
 *
 *   <taskId>        one of the ids in tests/lib/taskPrompts.ts
 *   --skill <name>  skill folder to vary (default: ingrain-security)
 *
 * For each variant it stages a throwaway plugin dir (the variant swapped in as the
 * target SKILL.md), writes the task to prompt.txt and a launch.sh, then opens one
 * terminal window per variant. Each window's session is captured to session.log.
 *
 * Everything OS-specific (how windows open, how the session is captured) lives
 * behind `ITerminalLauncher` in ./platform — selected by `getTerminalLauncher()`.
 * Everything in THIS file is platform-neutral. Today only macOS has a launcher;
 * on any other OS the factory throws a clear, actionable error.
 *
 * Run dirs land under tests/.variant-runs/<taskId>/<label>/ (git-ignored).
 */

import { join } from "@std/path";
import { PLUGIN_DIR } from "../lib/claudeRunner.ts";
import { shQuote } from "../lib/shell.ts";
import { discoverVariants, stageVariantPluginDir, type TVariant } from "../lib/variants.ts";
import { findTask, TASK_PROMPTS } from "../lib/taskPrompts.ts";
import {
  getTerminalLauncher,
  type ITerminalLauncher,
  type TTerminalJob,
} from "./platform/index.ts";

/** Where staged plugins, prompts, and logs go (git-ignored). */
const RUNS_ROOT = join(PLUGIN_DIR, "tests", ".variant-runs");

/** Skill folder names are lowercase-kebab; reject anything else (no path traversal). */
const SKILL_NAME_RE = /^[a-z0-9-]+$/;

/** Parse argv into { taskId, skill }. */
const parseArgs = (args: string[]): { taskId?: string; skill: string } => {
  let skill = "ingrain-security";
  const positionals: string[] = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--") {
      continue; // `deno task variants -- <id>` forwards the separator; ignore it
    } else if (args[i] === "--skill") {
      skill = args[++i] ?? "";
    } else {
      positionals.push(args[i]);
    }
  }
  return { taskId: positionals[0], skill };
};

const die = (msg: string): never => {
  console.error(`error: ${msg}`);
  Deno.exit(1);
};

/**
 * Write prompt.txt + launch.sh into a variant's run dir, returning the launch.sh
 * path. The launch.sh is the platform-neutral core (cd into a clean workspace,
 * run claude against the staged plugin); the launcher wraps the claude command
 * with its OS-specific session-capture tool.
 */
const writeRunScripts = async (
  launcher: ITerminalLauncher,
  runDir: string,
  stagedPluginDir: string,
  prompt: string,
): Promise<string> => {
  const workspace = join(runDir, "workspace");
  await Deno.mkdir(workspace, { recursive: true });

  const promptPath = join(runDir, "prompt.txt");
  const logPath = join(runDir, "session.log");
  const launchPath = join(runDir, "launch.sh");

  await Deno.writeTextFile(promptPath, prompt);

  // The prompt is read via `$(cat …)` so no prompt text reaches the shell as code.
  const claudeCmd = `claude --plugin-dir ${shQuote(stagedPluginDir)} "$(cat ${
    shQuote(promptPath)
  })"`;

  const launch = [
    "#!/usr/bin/env bash",
    "# Auto-generated by tests/variants/run.ts — interactive claude session for one variant.",
    `cd ${shQuote(workspace)}`,
    launcher.captureCommand(claudeCmd, logPath),
    "",
  ].join("\n");
  await Deno.writeTextFile(launchPath, launch);

  return launchPath;
};

const main = async () => {
  const { taskId, skill } = parseArgs(Deno.args);

  // Fail fast on an unsupported OS before staging anything.
  const launcher = getTerminalLauncher();

  if (!taskId) {
    die(`no task id given.\nAvailable tasks:\n${listTasks()}`);
  }
  const task = findTask(taskId!);
  if (!task) {
    die(`unknown task '${taskId}'.\nAvailable tasks:\n${listTasks()}`);
  }
  if (!SKILL_NAME_RE.test(skill)) {
    die(`invalid --skill '${skill}' (expected lowercase-kebab skill folder name)`);
  }

  const variants = await discoverVariants(skill);
  if (variants.length === 1) {
    console.warn(
      `note: skills/${skill} has only the baseline SKILL.md — nothing to compare. ` +
        `Drop SKILL1.md… into the folder to add variants. Launching the baseline anyway.`,
    );
  }

  const taskRoot = join(RUNS_ROOT, taskId!);
  const jobs: (TTerminalJob & { runDir: string })[] = [];

  for (const variant of variants) {
    const runDir = join(taskRoot, variant.label);
    await Deno.mkdir(runDir, { recursive: true });
    const pluginDir = await stageVariantPluginDir(skill, variant, runDir);
    const launchPath = await writeRunScripts(launcher, runDir, pluginDir, task!.prompt);
    jobs.push({ label: variant.label, launchPath, runDir });
  }

  await launcher.openWindows(jobs);
  printSummary(launcher, skill, task!, variants, jobs);
};

const listTasks = (): string =>
  TASK_PROMPTS.map((t) => `  ${t.id.padEnd(16)} ${t.label}`).join("\n");

const printSummary = (
  launcher: ITerminalLauncher,
  skill: string,
  task: { id: string; label: string },
  variants: TVariant[],
  jobs: { label: string; runDir: string }[],
): void => {
  console.log(
    `\nLaunched ${jobs.length} window(s) via ${launcher.name} for task '${task.id}' (${task.label})`,
  );
  console.log(`skill: ${skill}  ·  variants: ${variants.map((v) => v.label).join(", ")}\n`);
  for (const job of jobs) {
    console.log(`  ${job.label.padEnd(12)} ${job.runDir}`);
  }
  console.log(`\nTranscripts: <run dir>/session.log  ·  re-runs reuse these dirs.`);
};

main().catch((e) => die(e instanceof Error ? e.message : String(e)));
